name: pcp_flutter
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  design_system:
    git:
      url: git@github.com:Nasajon/flutter_design_system
      ref: main

  flutter_core:
    git:
      url: git@github.com:Nasajon/flutter_core
      ref: main

  flutter_global_dependencies:
    git:
      url: git@github.com:Nasajon/flutter_global_dependecies
      ref: main

  nsj_flutter_login:
    git:
      url: git@github.com:Nasajon/NasajonUI-Flutter-Login.git
      ref: main

  ana_l10n:
    git:
      url: https://github.com/Nasajon/ana_l10n
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  flutter_launcher_icons: 0.11.0
  triple_test: 2.0.0
  lints: ^2.0.0

flutter:

dependency_overrides:
  design_system:
    path: ../flutter_design_system

  flutter_core:
    path: ../flutter_core

  flutter_global_dependencies:
    path: ../flutter_global_dependencies

  nsj_flutter_login:
    path: ../NasajonUI-Flutter-Login

  ana_l10n:
    path: ../ana_l10n
